# Present yourself by first creating some variables that hold to the data such as your name, place of birth, age, favorite hobby etc. Then using the print() function output the information.  Example of the output:  'Hello my name is VARIABLE1 and my place of birth is VARIABLE2. I am VARIABLE3 years old....'.
# For reference on how to use the print() function check...
